Mon Jan 18 02:05:52 JST 2021
Mon Jan 18 19:36:40 JST 2021
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm16.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm32.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm64.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Traceback (most recent call last):
  File "selected_dropout4.py", line 68, in <module>
    with open(f'transfer_entropy_{model_name[:-8]}.toml', 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'transfer_entropy_fix_sclstm128.toml'
Mon Jan 18 23:19:50 JST 2021
Traceback (most recent call last):
  File "fix_train.py", line 24, in <module>
    cnn_def = importlib.import_module("{}".format(file_name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.fix_sclstm2048'
Traceback (most recent call last):
  File "fix_train.py", line 24, in <module>
    cnn_def = importlib.import_module("{}".format(file_name))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.fix_sclstm8192'
Mon Jan 18 23:19:52 JST 2021
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
Traceback (most recent call last):
  File "all_mysd.py", line 73, in <module>
    score = te_score
NameError: name 'te_score' is not defined
